spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
# none:不执行ddl
# create:每次加载hibernate时都会删除上一次的生成的表,根据model重新生成;
# create-drop:每次加载hibernate时根据model类生成表，但是sessionFactory一关闭,表就自动删除;
# update:第一次加载hibernate时根据model类会自动建立起表的结构,以后加载hibernate时根据model类自动更新表结构，即使表结构改变了但表中的行仍然存在不会删除以前的行。要注意的是当部署到服务器后，表结构是不会被马上建立起来的，是要等应用第一次运行起来后才会。
# validate:每次加载hibernate时，验证创建数据库表结构，只会和数据库中的表进行比较，不会创建新表，但是会插入新值。

logging:
  level:
    org.hibernate.SQL: debug

